### ISSUE TITLE
SP6000 is also supported

### ISSUE THREAD

**Issue by kisPocok** [Tertiush/ParadoxIP150v2#1]
Hi Tertiush,

Thank you for sharing this codes! It work like a charm with my SP6000 board + IP150. 

**MQTT**
I wasn't familiar with MQTT so it took a time to find a working server/broker. 
The easiest way to try it is a public broker. Choose one from here, enter it's ip to the `config.ini`.
https://github.com/mqtt/mqtt.github.io/wiki/public_brokers

The README must tell about it.
Thanks again!

**Comment by Tertiush** [comment]
Thanks for letting me know, will add to the list. Regarding MQTT I must admin I assumed people will know [obviously not always true], will add a one-liner. However I wouldn't encourage the use of public brokers with your alarm system due to privacy. thanks again

**Comment by radebebek** [comment]
kisPocok, are you edit some code in plugin and config.ini?
Because I have some error in log after connect to alarm system:
INFO: Socket connection closed bz remote host> -1
ERROR: attempting connection to ip module: NoneType OBJECT HAS NO ATTRIBUTE GETITEM

**Comment by radebebek** [comment]
NoneType means that instead of an instance of whatever Class or Object you think you're working with, you've actually got None. That usually means that an assignment or function call up above failed or returned an unexpected result.  
Maybe have missed something when configuring config.ini?
Are you working without problems with this plugin?
This plugin has nothing with burned IP150?

**Comment by kisPocok** [comment]
> This plugin has nothing with burned IP150?
Not at all. Over current/surge happened.
