### ISSUE TITLE
IP150 - Evo192 no Change status

### ISSUE THREAD

**Issue by dxcoco2** [Tertiush/ParadoxIP150v2#10]
I tried this script! MQTT and  alarm panel connected successfully, but when I send the commands "Paradox/C/P1/Arm" or Disarm seems to work, but it really does not change the alarm state ...
Any idea?

**Comment by Tertiush** [comment]
What is the console output? Can you hear a beep from the panel?

**Comment by dxcoco2** [comment]
Hi! 
The output:
Alarm: Control partition P1 to state: Arm

Buy i don't listen any beep from al alarm panel!




Inviato da iPhone

**Comment by dxcoco2** [comment]
No Idea?

**Comment by Tertiush** [comment]
Hi sorry for the delay was away from home...

I really can't think of anything other than the code just not being fully compatible with the EVO. I suggest you ask in https://github.com/Tertiush/ParadoxIP150v2/issues/5. There's some other guys with EVOs that might know. Otherwise try v1 of the code. Bypass and PGM won't work there, but ARM, etc. should.

**Comment by dxcoco2** [comment]
No problem... i've tried v1 but doesn't connect to alarm...i'm not interested to PGM...i want only Arm and Disarm the alarm...
I've set ip and port (not 8085 but 10000) but doesn't connect... :(

**Comment by Tertiush** [comment]
For v1 the port needed is your web port, not the software port. 10000 is
the default software port....

**Comment by dxcoco2** [comment]
Ah...i go to try!!!!

**Comment by dxcoco2** [comment]
Great! Work 100% with v1!
Thanks!!!!!

**Comment by danbba1** [comment]
to @dxcoco2 would you mind sharing your config.ini for EVO192? Of course, hiding sensitive data. Could not get it working. Thanks.
